### ISSUE TITLE
-- UNMET PEER DEPENDENCY react-native-vector-icons@^4.2.0  KKiapay

### ISSUE THREAD

**Issue by MOUTAIROU** [kkiapay/js-sdk#5]
when i installed kkpiay i get this error -- UNMET PEER DEPENDENCY react-native-vector-icons@^4.2.0  anyone know how can i fixe this issue

**Comment by issotina** [comment]
This error is not related to KkiaPay. Assuming you want to integrate kkiapay into your reactjs frontend, I recommend you instead use the kkiapay widget method. You have very intuitive documentation at this address: https://docs.kkiapay.me/v1/plugin-et-sdk/sdk-javascript
